# Generated by Django 3.2 on 2021-05-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sshConfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ssh_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('userpaaword', models.CharField(max_length=100)),
                ('ipaddress', models.CharField(max_length=20)),
            ],
        ),
    ]
