# Generated by Django 3.2 on 2021-05-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sshConfig', '0002_ssh_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssh_user',
            name='gourp_id',
            field=models.SmallIntegerField(default=0),
        ),
    ]
